version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - PORT=5000
      - JWT_SECRET=your_secret_here
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: ecommerce-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
